module App
{
  interface Account
  {
    void deposit(in unsigned long amount );
    void withdraw(in unsigned long amount );
    long balance();
  };
  interface Bank
  {
    Account create();
    void destroy(in Account a);
  };
};
