package App;


/**
* App/Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* mercredi 2 novembre 2016 11 h 50 CET
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
