package App;


/**
* App/Transaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* mercredi 2 novembre 2016 11 h 50 CET
*/

public final class Transaction implements org.omg.CORBA.portable.IDLEntity
{
  public int num = (int)0;
  public int amount = (int)0;
  public int account_source = (int)0;
  public int account_destination = (int)0;
  public boolean transaction_confirme = false;
  public int bank_source = (int)0;
  public int bank_dest = (int)0;

  public Transaction ()
  {
  } // ctor

  public Transaction (int _num, int _amount, int _account_source, int _account_destination, boolean _transaction_confirme, int _bank_source, int _bank_dest)
  {
    num = _num;
    amount = _amount;
    account_source = _account_source;
    account_destination = _account_destination;
    transaction_confirme = _transaction_confirme;
    bank_source = _bank_source;
    bank_dest = _bank_dest;
  } // ctor

} // class Transaction
