module App
{
  struct Transaction
  {
    long num;
    long amount;
    long account_source;
    long account_destination;
    boolean transaction_confirme;
    long bank_source;
    long bank_dest;
  };

  interface BankTransaction
  {
    boolean recevoirTransaction(in Transaction t);
    boolean confirmerTransaction(in Transaction t);
    long get_num();
  };

  interface BankCustomer
  {
    boolean create(in unsigned long num);
    boolean destroy(in unsigned long num);
    boolean deposit(in unsigned long amount, in unsigned long num);
    boolean withdraw(in unsigned long amount, in unsigned long num);
    boolean transfert(in unsigned long myNum, in unsigned long amount, in unsigned long numBank, in unsigned long num);
    boolean closeAccount(in unsigned long num);
    long balance(in unsigned long num);
    long get_num();
  };

  interface InterBank
  {
    boolean envoyerTransaction(in Transaction t);
    boolean confirmerTransaction(in Transaction t);
    boolean join(in unsigned long num);
    boolean desactivate_bank(in unsigned long num);
    long get_num();
  };
};
