package App;

/**
* App/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Thursday, November 3, 2016 3:57:44 PM CET
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public App.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (App.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.BankHelper.type ();
  }

}
