package App;


/**
* App/BankPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Friday, November 4, 2016 4:21:49 PM CET
*/

public abstract class BankPOA extends org.omg.PortableServer.Servant
 implements App.BankOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("create", new java.lang.Integer (0));
    _methods.put ("destroy", new java.lang.Integer (1));
    _methods.put ("deposit", new java.lang.Integer (2));
    _methods.put ("withdraw", new java.lang.Integer (3));
    _methods.put ("transfert", new java.lang.Integer (4));
    _methods.put ("balance", new java.lang.Integer (5));
    _methods.put ("recevoirTransaction", new java.lang.Integer (6));
    _methods.put ("confirmerTransaction", new java.lang.Integer (7));
    _methods.put ("get_num", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // App/Bank/create
       {
         int num = in.read_ulong ();
         boolean $result = false;
         $result = this.create (num);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // App/Bank/destroy
       {
         int num = in.read_ulong ();
         boolean $result = false;
         $result = this.destroy (num);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // App/Bank/deposit
       {
         int amount = in.read_ulong ();
         int num = in.read_ulong ();
         boolean $result = false;
         $result = this.deposit (amount, num);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // App/Bank/withdraw
       {
         int amount = in.read_ulong ();
         int num = in.read_ulong ();
         boolean $result = false;
         $result = this.withdraw (amount, num);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // App/Bank/transfert
       {
         int myNum = in.read_ulong ();
         int amount = in.read_ulong ();
         int numBank = in.read_ulong ();
         int num = in.read_ulong ();
         boolean $result = false;
         $result = this.transfert (myNum, amount, numBank, num);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // App/Bank/balance
       {
         int num = in.read_ulong ();
         int $result = (int)0;
         $result = this.balance (num);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // App/Bank/recevoirTransaction
       {
         App.Transaction t = App.TransactionHelper.read (in);
         boolean $result = false;
         $result = this.recevoirTransaction (t);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // App/Bank/confirmerTransaction
       {
         App.Transaction t = App.TransactionHelper.read (in);
         boolean $result = false;
         $result = this.confirmerTransaction (t);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // App/Bank/get_num
       {
         int $result = (int)0;
         $result = this.get_num ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/Bank:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Bank _this() 
  {
    return BankHelper.narrow(
    super._this_object());
  }

  public Bank _this(org.omg.CORBA.ORB orb) 
  {
    return BankHelper.narrow(
    super._this_object(orb));
  }


} // class BankPOA
