package App;


/**
* App/Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Friday, November 4, 2016 3:38:09 PM CET
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
