package App;


/**
* App/InterBankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Friday, November 4, 2016 3:38:09 PM CET
*/

public interface InterBankOperations 
{
  boolean envoyerTransaction (App.Transaction t);
  boolean confirmerTransaction (App.Transaction t);
  boolean join (int num);
} // interface InterBankOperations
