package App;


/**
* App/InterBank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Thursday, November 3, 2016 5:52:37 PM CET
*/

public interface InterBank extends InterBankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterBank
