package App;


/**
* App/InterBankPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Thursday, November 3, 2016 5:52:37 PM CET
*/

public abstract class InterBankPOA extends org.omg.PortableServer.Servant
 implements App.InterBankOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("envoyerTransaction", new java.lang.Integer (0));
    _methods.put ("confirmerTransaction", new java.lang.Integer (1));
    _methods.put ("join", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // App/InterBank/envoyerTransaction
       {
         App.Transaction t = App.TransactionHelper.read (in);
         boolean $result = false;
         $result = this.envoyerTransaction (t);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // App/InterBank/confirmerTransaction
       {
         App.Transaction t = App.TransactionHelper.read (in);
         boolean $result = false;
         $result = this.confirmerTransaction (t);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // App/InterBank/join
       {
         int num = in.read_ulong ();
         boolean $result = false;
         $result = this.join (num);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/InterBank:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InterBank _this() 
  {
    return InterBankHelper.narrow(
    super._this_object());
  }

  public InterBank _this(org.omg.CORBA.ORB orb) 
  {
    return InterBankHelper.narrow(
    super._this_object(orb));
  }


} // class InterBankPOA
