package App;


/**
* App/InterBankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Thursday, November 3, 2016 3:57:44 PM CET
*/

public interface InterBankOperations 
{
  void envoyerTransaction (App.Transaction t);
  void confirmerTransaction (App.Transaction t);
} // interface InterBankOperations
