package App;


/**
* App/InterBankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Thursday, November 3, 2016 4:53:32 PM CET
*/

public interface InterBankOperations 
{
  boolean envoyerTransaction (App.Transaction t);
  boolean confirmerTransaction (App.Transaction t);
} // interface InterBankOperations
